Add the title and copyright info
ubuntu-flutter-community/settings pull request #403
Opened 2022-11-24 13:04 UTC by YoussefLasheen

Fix for #385 

I solved this by saving the image's title to the file name and view it under the image.

- Change the saving directory to `/Documents/ImageOfTheDay/providername/image.jpeg`
- Created two new classes to make it easier to add more providers
- Format the Nasa copyright info to be like bing's
- Used HD image from the NASA's api if available

I wanted to embed the copyright info to the image actual metadata but couldn't do it.

2022-11-24 13:11 UTC, YoussefLasheen commented
Did it really just fail because of some trailing commas? :thinking:

2022-11-24 13:18 UTC, Jupi007 commented
Yes, there is a formatting analysing, to ensure code good practices and consistency :)

Which code editor are you using?
Because, with VS Code, there are Dart + Flutter extensions which provide automatic formatting and linting.

You can also run: `dart fix --apply`.
This will apply the recommended fix to the project.

2022-11-25 18:44 UTC, Jupi007 reviewed
Thanks very much @YoussefLasheen 
In term of code, it looks good for me :+1: 

I just have a few suggestion for the design:

- Use italic and grey text (like .75 of opacity) ;
- align the caption with the image by adding 6.0 of horizontal padding ;
- maybe also add a sizedbox between the caption and the Bing/Nasa selector (like 15.0).

![image](https://user-images.githubusercontent.com/36476595/204040854-3e93cc9e-23c2-4cfe-a691-2743a58e9169.png)

Also, it is not related to this PR as it is also in master, but the image doesn't load for me.

2022-11-25 20:36 UTC, YoussefLasheen commented
Should I add a fix for this and other unrelated commits(they're related to the wallpaper page) to this pr or should I open individual ones? @Jupi007

2022-11-25 20:52 UTC, Jupi007 commented
For the design change, please do it in this PR, as the caption as been introduced here.

For the other problem, I will open an issue.
If you want, I can assign you on it 🙂

2022-11-25 21:26 UTC, YoussefLasheen commented
I added the modifications that you asked for except the last 
>maybe also add a sizedbox between the caption and the Bing/Nasa selector (like 15.0).
Can you elaborate please?

2022-11-25 21:45 UTC, YoussefLasheen commented
Can you check now please?

2022-11-25 21:52 UTC, Jupi007 requested changes
Thanks, I added a few more comments 🙂

2022-11-25 21:52 UTC, Jupi007 commented on lib/view/pages/wallpaper/wallpaper_page.dart
> +                  model.pictureUri.split('/').last.replaceFirst('.jpeg', ''),
I didn't realize, but maybe the split and replace operation should be moved to the model?
So we could only call `model.caption` here.

2022-11-25 21:52 UTC, Jupi007 commented on lib/view/pages/wallpaper/wallpaper_page.dart
> +                padding: const EdgeInsets.only(left: 5, bottom: 15),
I think it should be symmetric, because currently, it can overflow a bit on the right.

```diff
-                padding: const EdgeInsets.only(left: 5, bottom: 15),
+                padding: const EdgeInsets.symmetric(horizontal: 5),
```

And replace the bottom padding by a sizedbox: `SizedBox(height: 15.0)`.

2022-11-25 23:31 UTC, Jupi007 approved these changes
LGFM 👍 
Thanks a lot @YoussefLasheen

2022-11-25 23:31 UTC, merged